# Python Groceseries iems Association Rule making

In [ ]:
#pip install mlxtend

In [38]:
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori,association_rules
import matplotlib.pyplot as plt

In [2]:
with open("groceries.csv") as f: # with open as file and read , groceries will be read as file read
    groceries = f.read()

In [5]:
#groceries # we input all input from excel which includes a new line of each items there

In [ ]:
 #type(groceries)
    #groceries # we have growseries list new line removed, insead separated by ','

In [3]:
# splitting the data into separate transactions using separator as "\n"
groceries = groceries.split("\n")

In [ ]:
 #groceries # all grocery items list of line split put into grocery list not string

In [7]:
groceries_list = [] # created a empty grocery list

In [8]:
for i in groceries:
    groceries_list.append(i.split(",")) # inside grocery list added all items of grocery  order of row

In [ ]:
#type(groceries_list)

In [10]:
#groceries_list

In [ ]:
#all_groceries_list = []

In [ ]:
# groceries_list # appended the list row items separately

In [11]:
from collections import Counter,OrderedDict # to count perfectly orderly

In [12]:
all_groceries_list = [i for item in groceries_list for i in item] # it means for in tiems inside of items

In [ ]:
 #all_groceries_list #list inside list checking

In [13]:
item_frequencies = Counter(all_groceries_list) # counting item frequency

In [14]:
item_frequencies = sorted(item_frequencies.items(),key = lambda x:x[1]) #

In [15]:
# Storing frequencies and items in separate variables 
frequencies = list(reversed([i[1] for i in item_frequencies]))
items = list(reversed([i[0] for i in item_frequencies]))

In [ ]:
#frequencies = list(sorted([i[1] for i in item_frequencies]))
#items = list(sorted([i[0] for i in item_frequencies]))

In [19]:
#items

In [ ]:
#frequencies

In [20]:
groceries_series  = pd.DataFrame(pd.Series(groceries_list))
#groceries_series = groceries_series.iloc[:9835,:] # removing the last empty transaction

#groceries_series.columns = ["transactions"]

In [21]:
groceries_series # grocery series created

                                                      0
0     [citrus fruit, semi-finished bread, margarine,...
1                      [tropical fruit, yogurt, coffee]
2                                          [whole milk]
3      [pip fruit, yogurt, cream cheese , meat spreads]
4     [other vegetables, whole milk, condensed milk,...
...                                                 ...
9831                                [cooking chocolate]
9832  [chicken, citrus fruit, other vegetables, butt...
9833  [semi-finished bread, bottled water, soda, bot...
9834  [chicken, tropical fruit, other vegetables, vi...
9835                                                 []

[9836 rows x 1 columns]

In [22]:
groceries_series.to_csv("Grocery series dataframe.csv") # saved df series list to a excel file

In [24]:
groceries_series = groceries_series.iloc[:9835,:] # removing the last empty transaction

In [28]:
groceries_series.tail() # removed lasst transaction

                                           Transactions
9830  [sausage, chicken, beef, hamburger meat, citru...
9831                                [cooking chocolate]
9832  [chicken, citrus fruit, other vegetables, butt...
9833  [semi-finished bread, bottled water, soda, bot...
9834  [chicken, tropical fruit, other vegetables, vi...

In [27]:
groceries_series.columns = ["Transactions"]

In [31]:
# creating a dummy columns for the each item in each transactions ... Using column names as item name
X = groceries_series['Transactions'].str.join(sep='*').str.get_dummies(sep='*')

In [33]:
X

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,baby food,bags,baking powder,bathroom cleaner,beef,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9830,0,0,0,0,0,0,0,0,0,1,...,0,0,0,1,0,0,0,1,0,0
9831,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9832,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
9833,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9834,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [37]:
frequent_itemsets = apriori(X, min_support=0.005, max_len=3,use_colnames = True)

In [34]:
X.to_excel("output.xlsx") # the output file for further operation and action is now saved to computer

### Implementing Association rule

In [45]:
frequent_itemsets.head() # this is percentage support and items visualization

    support                 itemsets
0  0.008033  (Instant food products)
1  0.033452               (UHT-milk)
2  0.017692          (baking powder)
3  0.052466                   (beef)
4  0.033249                (berries)

In [46]:
Arules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)

In [47]:
Arules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(bottled water),(UHT-milk),0.110524,0.033452,0.007321,0.066237,1.980074,0.003624,1.035111
1,(UHT-milk),(bottled water),0.033452,0.110524,0.007321,0.218845,1.980074,0.003624,1.138668
2,(other vegetables),(UHT-milk),0.193493,0.033452,0.008134,0.042039,1.256694,0.001662,1.008964
3,(UHT-milk),(other vegetables),0.033452,0.193493,0.008134,0.243161,1.256694,0.001662,1.065626
4,(rolls/buns),(UHT-milk),0.183935,0.033452,0.006406,0.034826,1.041071,0.000253,1.001423
...,...,...,...,...,...,...,...,...,...
2695,"(whole milk, whipped/sour cream)",(yogurt),0.032232,0.139502,0.010880,0.337539,2.419607,0.006383,1.298943
2696,"(yogurt, whipped/sour cream)",(whole milk),0.020742,0.255516,0.010880,0.524510,2.052747,0.005580,1.565719
2697,(whole milk),"(yogurt, whipped/sour cream)",0.255516,0.020742,0.010880,0.042579,2.052747,0.005580,1.022807
2698,(yogurt),"(whole milk, whipped/sour cream)",0.139502,0.032232,0.010880,0.077988,2.419607,0.006383,1.049627
2699,(whipped/sour cream),"(whole milk, yogurt)",0.071683,0.056024,0.010880,0.151773,2.709053,0.006864,1.112881